name: zhuanyemuqian

on:
  workflow_dispatch:
  schedule:
    - cron: '8 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuanyemuqian
        env:
          thlws1: ${{ secrets.thlws1 }}
        run: |
          echo $thlws1 | jq -r .mw35723 | /bin/bash
          echo $uyng39534 | jq -r .igbka234 | /bin/bash
          echo $t4 | jq -r .ngno968 | /bin/bash
          echo $ljm163 | jq -r .mi0988 | /bin/bash
          echo $rnv4 | jq -r .yetu948 | /bin/bash
          echo $tb2 | jq -r .evfp0 | /bin/bash

